package wb.plugin.wbutils.adapters.commands;

public enum DealInfoResult {

    INVALID_INPUT, DEAL_NOT_FOUND, OWNER_CHANGED, GOLD_COINS_CHANGED, SILVER_COINS_CHANGED, COPPER_COINS_CHANGED,
    MATERIALS_CHANGED, UNKNOWN_STAT, DEAL_OWNER_RESET
}
