name: wbUtils
version: '${project.version}'
main: wb.plugin.wbutils.wbUtils
api-version: 1.19
authors: [ sst4nk0 ]
description: A plugin with all essential utilities for this server.
depend: [PlaceholderAPI]
commands:
  clearchat:
    description: Clears the entire chat.
    permission: wbutils.clearchat
    usage: /<command>
    aliases:
      - cc
  dealinfo:
    description: Set the deal's stats
    permission: wbutils.dealinfo
    usage: /<command> <deal_id> <stat> <value>
  payday:
    description: Grants an extra payday event
    permission: wbutils.payday
    usage: /<command> <multiplier>
  dealrecount:
    description: System command | Recounts coins in deal storage from low-tiers to higer-tiers
    permission: wbutils.dealrecount
    usage: /<command> <deal_id> <nickname>
  dealtakeitems:
    description: System command | Removes selected items from player's inventory and sends them to material storage of a deal
    permission: wbutils.takeitems
    usage: /<command> <nickname> <deal_id> <itemedit_name1> <itemedit_nameX>
  dealbuy:
    description: System command
    permission: wbutils.dealbuy
  dospecialaction:
    description: System command
  dospecialaction2:
    description: System command
  dospecialaction3:
    description: System command
  purchasepayment:
    description: System command
    permission: wbutils.purchasepayment